local L = LibStub('AceLocale-3.0'):NewLocale('XFaction', 'ruRU')
if not L then return end
-- Translator ZamestoTV
--=========================================================================
-- Generic One Word Translations
--=========================================================================
L['ALLIANCE'] = 'Альянс'
L['HORDE'] = 'Орда'
L['NAME'] = 'Имя'
L['RACE'] = 'Раса'
L['LEVEL'] = 'Уровень'
L['REGION'] = 'Регион'
L['REALM'] = 'Сервер'
L['REALMS'] = 'Сервера'
L['GUILD'] = 'Гильдия'
L['GUILDS'] = 'Гильдии'
L['GUILD_NAME'] = 'Название гильдии'
L['TEAM'] = 'Команда'
L['RANK'] = 'Ранг'
L['HERO'] = 'Герой'
L['TAG'] = 'Тег'
L['NONXFACTION'] = 'Пользователи без XFaction'
L['MYTHIC'] = 'Эпохальный'
L['ZONE'] = 'Зона'
L['ID'] = 'ID'
L['NOTE'] = 'Заметка'
L['CLASS'] = 'Класс'
L['CONFEDERATE'] = 'Конфедерация'
L['CONFEDERATE_NAME'] = 'Название конфедерации'
L['CONFEDERATE_INITIALS'] = 'Инициалы конфедерации'
L['COLLECTION'] = 'Коллекция'
L['MOTD'] = 'Сообщение дня'
L['FACTION'] = 'Фракция'
L['PROFESSION'] = 'Профессия'
L['SPEC'] = 'Специализация'
L['ENABLE'] = 'Включить'
L['CHAT'] = 'Чат'
L['ACHIEVEMENT'] = 'Достижение'
L['DATATEXT'] = 'DataText'
L['SUPPORT'] = 'Поддержка'
L['RESOURCES'] = 'Ресурсы'
L['DISCORD'] = 'Discord'
L['GITHUB'] = 'GitHub'
L['DEV'] = 'Разработка'
L['DESCRIPTION'] = 'Описание'
L['GENERAL'] = 'Общие'
L['DISCLAIMER'] = 'Отказ от ответственности'
L['TRANSLATIONS'] = 'Переводы'
L['FAQ'] = 'ЧАВО'
L['CHANNEL'] = 'Канал'
L['CHANNEL_NAME'] = 'Название канала'
L['CHANNEL_PASSWORD'] = 'Пароль канала'
L['INDEX'] = 'Индекс'
L['DUNGEON'] = 'Очки М+'
L['MYTHICKEY'] = 'Ключ'
L['ACHIEVEMENT_EARNED'] = 'получил достижение'
L['CHAT_LOGOUT'] = 'вышел из сети.'
L['CHAT_JOIN_GUILD'] = 'вступил в гильдию.'
L['CHAT_JOIN_CONFEDERATE'] = 'вступил в конфедерацию.'
L['EXPLORE'] = 'Исследование'
L['VERSION'] = 'Версия'
L['MAIN'] = 'Мейн'
L['LABEL'] = 'Метка'
L['CUSTOMER'] = 'Заказчик'
L['LINKS'] = 'Ссылки'
L['PM'] = 'Менеджер проекта'
L['USAGE'] = 'Использование'
L['EVENT'] = 'Событие'
L['FRIEND'] = 'Друг'
L['LINK'] = 'Ссылка'
L['PLAYER'] = 'Игрок'
L['PROFESSION'] = 'Профессия'
L['SPEC'] = 'Специализация'
L['TARGET'] = 'Цель'
L['TEAM'] = 'Команда'
L['TEAMS'] = 'Команды'
L['TIMER'] = 'Таймер'
L['ITEMLEVEL'] = 'Уровень предметов'
L['CENTER'] = 'По центру'
L['LEFT'] = 'Слева'
L['RIGHT'] = 'Справа'
L['ALIGNMENT'] = 'Выравнивание'
L['ORDER'] = 'Порядок'
L['RAID'] = 'Рейд'
L['PVP'] = 'PvP'
L['NODE'] = 'Узел'
L['ORDER'] = 'Порядок'
L['ROSTER'] = 'Состав'
L['DEBUG'] = 'Отладка'
L['CONTINENT'] = 'Континент'
L['LOCATION'] = 'Местоположение'
L['SETUP'] = 'Настройка'
L['COMPRESSION'] = 'Сжатие'
L['SAVE'] = 'Сохранить'
L['VERBOSITY'] = 'Подробность'
L['RAIDERIO'] = 'RaiderIO'
L['GRAPHICS'] = 'Графика'
L['INSTRUCTIONS'] = 'Инструкции'
L['INITIALS'] = 'Инициалы'
L['COMPRESS'] = 'Сжать'
L['GUILD_INFO'] = 'Информация о гильдии'
L['HOW_TO'] = 'Как сделать'
L['ADDONS'] = 'Аддоны'
L['ABOUT'] = 'О аддоне'
L['CHANGE_LOG'] = 'Журнал изменений'
L['SUMMARY'] = 'Сводка'
L['NEW'] = 'Новое'
L['IMPROVEMENTS'] = 'Улучшения'
L['COMMUNICATION'] = 'Общение'
L['METRICS'] = 'Метрики'
L['CRAFTING'] = 'Ремесло'
L['ITEM'] = 'Предмет'
L['AUDIT'] = 'Аудит'
L['US'] = 'US'
L['KR'] = 'KR'
L['EU'] = 'EU'
L['TW'] = 'TW'
L['CN'] = 'CN'
--=========================================================================
-- General (tab) Specific
--=========================================================================
L['GENERAL_DESCRIPTION'] = 'Включает видимость состава и общение между гильдиями конфедерации, включая гильдии на других серверах и другой фракции.\n\nБольшинство аддонов используют API, который проходит через невидимый (для пользователя) канал для общения. Однако каналы изолированы по серверу и фракции, поэтому GreenWall предоставляет видимость только другим членам Альянса на том же сервере.\n\nКаналы сообществ кросс-реалм/фракционные, но не имеют "невидимых" вызовов API. Battle.Net (BNet) имеет. Этот аддон использует BNet для отправки общения между серверами/фракциями, невидимо для пользователя. За дополнительными деталями обращайтесь к ЧАВО или Wiki на вкладке Поддержка.'
L['GENERAL_CONFIGURATION'] = 'Основные функции'
L['GENERAL_GUILD_MESSAGES'] = 'Сообщения гильдии'
L['GENERAL_GUILD_CHAT'] = 'Объединённый чат гильдии между гильдиями/серверами/фракциями в конфедерации.'
L['GENERAL_GUILD_CHAT_ACHIEVEMENT'] = 'Личные достижения пересылаются членам конфедерации в других гильдиях.'
L['GENERAL_SYSTEM_MESSAGES'] = 'Системные сообщения'
L['GENERAL_SYSTEM_LOGIN'] = 'Получать уведомления, когда игрок с аддоном входит/выходит из сети в конфедерации.'
L['GENERAL_DATA_BROKERS'] = 'Data Brokers'
L['GENERAL_DTGUILD'] = 'Полная видимость состава конфедерации через data broker Guild (X), включая: имя, фракцию, уровень, специализацию, класс, расу, сервер, гильдию, команду, ранг, зону, профессии, рейтинг PvP и максимальный уровень предметов.'
L['GENERAL_DTLINKS'] = 'Видимость активных BNet-связей в конфедерации, используемых аддоном, через data broker Links (X).'
L['GENERAL_DTMETRICS'] = 'Отображает статистическую информацию о производительности аддона через data broker Metrics (X).'
L['GENERAL_DTTOKEN'] = 'WoW-токен (X): Просмотр текущей рыночной цены WoW-токенов'
--=========================================================================
-- Channel Specific
--=========================================================================
L['CHANNEL_LAST'] = 'Канал аддона в конце'
L['CHANNEL_LAST_TOOLTIP'] = 'XFaction всегда помещает свой канал последним в списке каналов. Каналы сообществ игнорируются из-за бага API Blizzard.'
L['CHANNEL_COLOR'] = 'Окраска каналов по имени'
L['CHANNEL_COLOR_TOOLTIP'] = 'Переключает с окраски по номеру (по умолчанию Blizzard) на окраску по имени'
--=========================================================================
-- Chat Specific
--=========================================================================
L['CHAT_CCOLOR'] = 'Настроить цвет'
L['CHAT_CCOLOR_TOOLTIP'] = 'Настроить цвета чата XFaction.'
L['CHAT_GUILD_DESCRIPTION'] = 'Эти опции контролируют отображение сообщений чата гильдии в окне чата.'
L['CHAT_GUILD'] = 'Чат гильдии'
L['CHAT_GUILD_TOOLTIP'] = 'Видеть чат гильдии кросс-реалм/фракций'
L['CHAT_FACTION'] = 'Показывать фракцию'
L['CHAT_FACTION_TOOLTIP'] = 'Показывать иконку фракции отправителя'
L['CHAT_FCOLOR'] = 'Окраска по фракции'
L['CHAT_FCOLOR_TOOLTIP'] = 'Окрашивать чат XFaction в цвета фракций.'
L['CHAT_GUILD_NAME'] = 'Показывать название гильдии'
L['CHAT_GUILD_NAME_TOOLTIP'] = 'Показывать короткое название гильдии отправителя'
L['CHAT_MAIN'] = 'Показывать имя мейна'
L['CHAT_MAIN_TOOLTIP'] = 'Показывать имя мейна отправителя, если это альт'
L['CHAT_FONT_COLOR'] = 'Цвет шрифта'
L['CHAT_FONT_ACOLOR'] = 'Цвет Альянса'
L['CHAT_FONT_HCOLOR'] = 'Цвет Орды'
L['CHAT_ACHIEVEMENT_DESCRIPTION'] = 'Эти опции контролируют отображение сообщений о достижениях гильдии в окне чата.'
L['CHAT_ACHIEVEMENT_TOOLTIP'] = 'Видеть личные достижения кросс-реалм/фракций'
L['CHAT_ONLINE'] = 'В сети/Не в сети'
L['CHAT_ONLINE_DESCRIPTION'] = 'Эти опции контролируют системные сообщения о входе/выходе членов гильдии.'
L['CHAT_ONLINE_TOOLTIP'] = 'Показывать сообщения о входе/выходе игроков на других серверах/фракциях'
L['CHAT_ONLINE_SOUND'] = 'Проигрывать звук'
L['CHAT_ONLINE_SOUND_TOOLTIP'] = 'Проигрывать звук, когда любой член конфедерации входит в сеть'
L['CHAT_LOGIN'] = 'вошёл в сеть.'
L['CHAT_LOGOUT'] = 'вышел из сети.'
L['CHAT_ACHIEVEMENT'] = 'получил достижение'
L['CHAT_NO_PLAYER_FOUND'] = 'Игрок с именем '
L['CHAT_CHANNEL_DESCRIPTION'] = 'Эти опции контролируют поведение пользовательского канала аддона.'
L['CHAT_CRAFTING_DESCRIPTION'] = 'Эти опции контролируют уведомления о заказах на ремесло.'
L['CHAT_CRAFTING_NEW'] = 'Новые заказы'
L['CHAT_CRAFTING_NEW_TOOLTIP'] = 'Отображать сообщения в чате о новых размещённых заказах.'
L['NEW_GUILD_CRAFTING_ORDER'] = 'создал новый гильдейский заказ на ремесло для %s.'
L['NEW_PERSONAL_CRAFTING_ORDER'] = 'отправил %s личный заказ на ремесло для %s.'
L['CHAT_CRAFTING_TOOLTIP'] = 'Получать уведомления о заказах на ремесло кросс-реалм/фракций.'
L['CHAT_CRAFTING_GUILD'] = 'Гильдейские заказы'
L['CHAT_CRAFTING_GUILD_TOOLTIP'] = 'Получать уведомления о гильдейских заказах на ремесло кросс-реалм/фракций.'
L['CHAT_CRAFTING_PERSONAL'] = 'Личные заказы'
L['CHAT_CRAFTING_PERSONAL_TOOLTIP'] = 'Получать уведомления о полученных личных заказах на ремесло.'
L['CHAT_CRAFTING_PROFESSION'] = 'Только мои профессии'
L['CHAT_CRAFTING_PROFESSION_TOOLTIP'] = 'Показывать заказы только для профессий этого персонажа.'
--=========================================================================
-- Addons Specific
--=========================================================================
L['CONFEDERATE_INITIALS'] = 'Инициалы конфедерации'
L['CONFEDERATE_NAME'] = 'Название конфедерации'
L['GUILD_INITIALS'] = 'Инициалы гильдии'
L['NAMEPLATE_GUILD_NAME_TOOLTIP'] = 'Заменять название гильдии на выбранный вариант, если гильдия входит в конфедерацию'
L['ELVUI'] = 'ElvUI'
L['ADDON_ELVUI_DESCRIPTION'] = 'ElvUI: доступны теги uOF, которые можно использовать в Unitframes и Nameplates. См. раздел Available Tags в настройках ElvUI.'
L['ADDON_ELVUI_CONFEDERATE'] = 'Отображать название конфедерации, если входит в неё, иначе название гильдии'
L['ADDON_ELVUI_CONFEDERATE_INITIALS'] = 'Отображать инициалы конфедерации, если входит в неё'
L['ADDON_ELVUI_GUILD_INITIALS'] = 'Отображать инициалы гильдии вместо полного названия, если входит в конфедерацию'
L['ADDON_ELVUI_MAIN'] = "Отображать имя мейна игрока, если известно, иначе текущее имя"
L['ADDON_ELVUI_MAIN_PARENTHESIS'] = "Отображать имя мейна игрока, если известно, в (скобках)"
L['ADDON_ELVUI_TEAM'] = "Отображать рейдовую команду игрока"
L['ADDON_ELVUI_MEMBER_ICON'] = 'Отображать иконку, обозначающую членство игрока в конфедерации'
L['NAMEPLATE_ICON'] = 'Иконка члена'
L['NAMEPLATE_ICON_TOOLTIP'] = 'Отображать иконку рядом с именем членов конфедерации'
L['NAMEPLATE_PLAYER_MAIN'] = 'Имя мейна'
L['NAMEPLATE_PLAYER_MAIN_TOOLTIP'] = "Добавлять к имени юнита имя мейна игрока"
L['NAMEPLATE_GUILD_HIDE'] = 'Скрывать не-конфедеративные'
L['NAMEPLATE_GUILD_HIDE_TOOLTIP'] = 'Скрывать теги гильдий, не входящих в конфедерацию'
L['WIM'] = 'WIM'
L['RAIDERIO'] = 'RaiderIO'
L['ADDON_WIM_DESCRIPTION'] = 'WIM: Перенаправлять сообщения конфедерации в WIM, если включён чат гильдии.'
L['ADDON_RAIDERIO'] = 'RaiderIO: Обеспечивать видимость очков рейда/М+ для всего состава.'
--=========================================================================
-- DataText Specific
--=========================================================================
L['DT_HEADER_CONFEDERATE'] = 'Конфедерация: |cffffffff%s|r'
L['DT_HEADER_GUILD'] = 'Гильдия: |cffffffff%s|r'
L['DT_CONFIG_BROKER'] = 'Показывать поля Broker'
L['DT_CONFIG_LABEL_TOOLTIP'] = 'Показывать метку broker'
L['DT_CONFIG_NONXFACTION_TOOLTIP'] = 'Показывать пользователей без XFaction, работает только для локальной гильдии'
L['DT_CONFIG_FACTION_TOOLTIP'] = 'Показывать количество по фракциям в метке broker'
L['DT_CONFIG_FONT'] = 'Шрифт'
L['DT_CONFIG_FONT_SIZE'] = 'Размер шрифта'
L['DT_CONFIG_FONT_TOOLTIP'] = 'Выбрать стиль шрифта'
L['DT_CONFIG_FONT_SIZE_TOOLTIP'] = 'Выбрать размер шрифта'
L['DTGENERAL_DESCRIPTION'] = 'Настройки, применяемые ко всем data brokers XFaction'
-------------------------
-- DTGuild (X)
-------------------------
-- Broker name
L['DTGUILD_NAME'] = 'Гильдия (X)'
L['DTGUILD_DESCRIPTION'] = 'Data broker гильдии отображает полный состав конфедерации.'
-- Config
L['DTGUILD_BROKER_HEADER'] = 'Настройки Broker'
L['DTGUILD_SELECT_COLUMN'] = 'Выбрать колонку'
L['DTGUILD_SELECT_COLUMN_TOOLTIP'] = 'Выбрать колонку из списка для настройки'
L['DTGUILD_CONFIG_SORT'] = 'Колонка сортировки по умолчанию'
L['DTGUILD_CONFIG_HEADER'] = 'Настройки заголовка'
L['DTGUILD_CONFIG_SIZE'] = 'Размер окна'
L['DTGUILD_CONFIG_CONFEDERATE_TOOLTIP'] = 'Показывать название конфедерации'
L['DTGUILD_CONFIG_CONFEDERATE_DISABLED'] = 'Должно быть включено минимум пять колонок'
L['DTGUILD_CONFIG_GUILD_TOOLTIP'] = 'Показывать название текущей гильдии'
L['DTGUILD_CONFIG_MOTD_TOOLTIP'] = 'Показывать сообщение дня гильдии'
L['DTGUILD_CONFIG_COLUMN_HEADER'] = 'Настройки колонок'
L['DTGUILD_CONFIG_COLUMN_ENABLE_MAIN'] = 'Добавлять мейн к имени'
L['DTGUILD_CONFIG_COLUMN_ACHIEVEMENT_TOOLTIP'] = 'Показывать общее количество очков достижений игрока'
L['DTGUILD_CONFIG_COLUMN_ACHIEVEMENT_ORDER_TOOLTIP'] = 'Номер колонки для отображения очков достижений'
L['DTGUILD_CONFIG_COLUMN_ACHIEVEMENT_ALIGNMENT_TOOLTIP'] = 'Выравнивание текста очков достижений'
L['DTGUILD_CONFIG_COLUMN_DUNGEON_TOOLTIP'] = 'Показывать очки мифик+ игрока'
L['DTGUILD_CONFIG_COLUMN_DUNGEON_ORDER_TOOLTIP'] = 'Номер колонки для отображения рейтинга мифик+'
L['DTGUILD_CONFIG_COLUMN_DUNGEON_ALIGNMENT_TOOLTIP'] = 'Выравнивание текста рейтинга мифик+'
L['DTGUILD_CONFIG_COLUMN_FACTION_TOOLTIP'] = 'Показывать иконку фракции игрока'
L['DTGUILD_CONFIG_COLUMN_FACTION_ORDER_TOOLTIP'] = 'Номер колонки для отображения иконки фракции'
L['DTGUILD_CONFIG_COLUMN_FACTION_ALIGNMENT_TOOLTIP'] = 'Выравнивание иконки фракции в колонке'
L['DTGUILD_CONFIG_COLUMN_GUILD_TOOLTIP'] = 'Показывать название гильдии игрока'
L['DTGUILD_CONFIG_COLUMN_GUILD_ORDER_TOOLTIP'] = 'Номер колонки для отображения названия гильдии'
L['DTGUILD_CONFIG_COLUMN_GUILD_ALIGNMENT_TOOLTIP'] = 'Выравнивание текста названия гильдии'
L['DTGUILD_CONFIG_COLUMN_ITEMLEVEL_TOOLTIP'] = 'Показывать максимальный уровень предметов игрока'
L['DTGUILD_CONFIG_COLUMN_ITEMLEVEL_ORDER_TOOLTIP'] = 'Номер колонки для отображения уровня предметов'
L['DTGUILD_CONFIG_COLUMN_ITEMLEVEL_ALIGNMENT_TOOLTIP'] = 'Выравнивание текста уровня предметов'
L['DTGUILD_CONFIG_COLUMN_LEVEL_TOOLTIP'] = 'Показывать уровень игрока'
L['DTGUILD_CONFIG_COLUMN_LEVEL_ORDER_TOOLTIP'] = 'Номер колонки для отображения уровня игрока'
L['DTGUILD_CONFIG_COLUMN_LEVEL_ALIGNMENT_TOOLTIP'] = 'Выравнивание текста уровня игрока'
L['DTGUILD_CONFIG_COLUMN_MAIN_TOOLTIP'] = 'Показывать имя мейна игрока, если на альте'
L['DTGUILD_CONFIG_COLUMN_NAME_ORDER_TOOLTIP'] = 'Номер колонки для отображения имени игрока'
L['DTGUILD_CONFIG_COLUMN_NAME_ALIGNMENT_TOOLTIP'] = 'Выравнивание текста имени игрока'
L['DTGUILD_CONFIG_COLUMN_NOTE_TOOLTIP'] = 'Показывать заметку игрока'
L['DTGUILD_CONFIG_COLUMN_NOTE_ORDER_TOOLTIP'] = 'Номер колонки для отображения заметки игрока'
L['DTGUILD_CONFIG_COLUMN_NOTE_ALIGNMENT_TOOLTIP'] = 'Выравнивание текста заметки игрока'
L['DTGUILD_CONFIG_COLUMN_PROFESSION_TOOLTIP'] = 'Показывать иконки профессий игрока'
L['DTGUILD_CONFIG_COLUMN_PROFESSION_ORDER_TOOLTIP'] = 'Номер колонки для отображения иконок профессий'
L['DTGUILD_CONFIG_COLUMN_PROFESSION_ALIGNMENT_TOOLTIP'] = 'Выравнивание иконок профессий в колонке'
L['DTGUILD_CONFIG_COLUMN_PVP_TOOLTIP'] = 'Показывать наивысший рейтинг PvP игрока'
L['DTGUILD_CONFIG_COLUMN_PVP_ORDER_TOOLTIP'] = 'Номер колонки для отображения рейтинга PvP'
L['DTGUILD_CONFIG_COLUMN_PVP_ALIGNMENT_TOOLTIP'] = 'Выравнивание текста рейтинга PvP'
L['DTGUILD_CONFIG_COLUMN_RACE_TOOLTIP'] = 'Показывать расу игрока'
L['DTGUILD_CONFIG_COLUMN_RACE_ORDER_TOOLTIP'] = 'Номер колонки для отображения расы игрока'
L['DTGUILD_CONFIG_COLUMN_RACE_ALIGNMENT_TOOLTIP'] = 'Выравнивание текста расы игрока'
L['DTGUILD_CONFIG_COLUMN_RAID_TOOLTIP'] = 'Показывать наивысший прогресс рейда игрока'
L['DTGUILD_CONFIG_COLUMN_RAID_ORDER_TOOLTIP'] = 'Номер колонки для отображения прогресса рейда'
L['DTGUILD_CONFIG_COLUMN_RAID_ALIGNMENT_TOOLTIP'] = 'Выравнивание текста прогресса рейда'
L['DTGUILD_CONFIG_COLUMN_RANK_TOOLTIP'] = 'Показывать ранг игрока'
L['DTGUILD_CONFIG_COLUMN_RANK_ORDER_TOOLTIP'] = 'Номер колонки для отображения ранга игрока'
L['DTGUILD_CONFIG_COLUMN_RANK_ALIGNMENT_TOOLTIP'] = 'Выравнивание текста ранга игрока'
L['DTGUILD_CONFIG_COLUMN_REALM_TOOLTIP'] = 'Показывать название сервера игрока'
L['DTGUILD_CONFIG_COLUMN_REALM_ORDER_TOOLTIP'] = 'Номер колонки для отображения названия сервера'
L['DTGUILD_CONFIG_COLUMN_REALM_ALIGNMENT_TOOLTIP'] = 'Выравнивание текста названия сервера'
L['DTGUILD_CONFIG_COLUMN_SPEC_TOOLTIP'] = 'Показывать иконку специализации игрока'
L['DTGUILD_CONFIG_COLUMN_SPEC_ORDER_TOOLTIP'] = 'Номер колонки для отображения иконки специализации'
L['DTGUILD_CONFIG_COLUMN_SPEC_ALIGNMENT_TOOLTIP'] = 'Выравнивание иконки специализации в колонке'
L['DTGUILD_CONFIG_COLUMN_HERO_TOOLTIP'] = 'Показывать иконку героической специализации игрока'
L['DTGUILD_CONFIG_COLUMN_HERO_ORDER_TOOLTIP'] = 'Номер колонки для отображения иконки героической специализации'
L['DTGUILD_CONFIG_COLUMN_HERO_ALIGNMENT_TOOLTIP'] = 'Выравнивание иконки героической специализации в колонке'
L['DTGUILD_CONFIG_COLUMN_TEAM_TOOLTIP'] = 'Показывать название команды игрока'
L['DTGUILD_CONFIG_COLUMN_TEAM_ORDER_TOOLTIP'] = 'Номер колонки для отображения названия команды'
L['DTGUILD_CONFIG_COLUMN_TEAM_ALIGNMENT_TOOLTIP'] = 'Выравнивание текста названия команды'
L['DTGUILD_CONFIG_COLUMN_VERSION_TOOLTIP'] = 'Показывать версию XFaction игрока'
L['DTGUILD_CONFIG_COLUMN_VERSION_ORDER_TOOLTIP'] = 'Номер колонки для отображения версии XFaction'
L['DTGUILD_CONFIG_COLUMN_VERSION_ALIGNMENT_TOOLTIP'] = 'Выравнивание текста версии XFaction'
L['DTGUILD_CONFIG_COLUMN_LOCATION_TOOLTIP'] = 'Показывать текущее местоположение игрока'
L['DTGUILD_CONFIG_COLUMN_LOCATION_ORDER_TOOLTIP'] = 'Номер колонки для отображения местоположения'
L['DTGUILD_CONFIG_COLUMN_LOCATION_ALIGNMENT_TOOLTIP'] = 'Выравнивание текста местоположения'
L['DTGUILD_CONFIG_COLUMN_MYTHICKEY_TOOLTIP'] = 'Показывать текущий эпохальный ключ игрока'
L['DTGUILD_CONFIG_COLUMN_MYTHICKEY_ORDER_TOOLTIP'] = 'Номер колонки для отображения ключа'
L['DTGUILD_CONFIG_COLUMN_MYTHICKEY_ALIGNMENT_TOOLTIP'] = 'Выравнивание текста ключа'
L['DTGUILD_CONFIG_SORT_TOOLTIP'] = 'Выбрать колонку сортировки по умолчанию'
L['DTGUILD_CONFIG_SIZE_TOOLTIP'] = 'Выбрать максимальную высоту окна перед началом прокрутки'
--=========================================================================
-- Confederate Specific
--=========================================================================
L['CONFEDERATE_CONFIG_BUILDER'] = 'Конструктор конфигурации'
L['CONFEDERATE_GENERATE'] = 'Сгенерировать'
L['CONFEDERATE_LOAD'] = 'Загрузить'
-------------------------
-- DTLinks (X)
-------------------------
-- Broker name
L['DTLINKS_NAME'] = 'Связи (X)'
L['DTLINKS_DESCRIPTION'] = 'Data broker Связи отображает все активные BNet-связи, используемые аддоном в данный момент.'
-- Header
L['DTLINKS_HEADER_LINKS'] = 'Активные BNet-связи: |cffffffff%d|r'
-------------------------
-- DTMetrics
-------------------------
L['DTMETRICS_NAME'] = 'Метрики (X)'
L['DTMETRICS_DESCRIPTION'] = 'Data broker Метрики отображает статистическую информацию о производительности XFaction.'
L['DTMETRICS_HEADER'] = 'Метрики с: |cffffffff%02d:%02d|r (Сервер)'
L['DTMETRICS_RATE'] = 'Средняя скорость'
L['DTMETRICS_RATE_TOOLTIP'] = '1 — среднее в секунду, 60 — среднее в минуту и т.д.'
L['DTMETRICS_HEADER_METRIC'] = 'Метрика'
L['DTMETRICS_HEADER_TOTAL'] = 'Всего'
L['DTMETRICS_HEADER_AVERAGE'] = 'Среднее'
L['DTMETRICS_BNET_SEND'] = 'Отправлено BNet'
L['DTMETRICS_BNET_RECEIVE'] = 'Получено BNet'
L['DTMETRICS_CHANNEL_RECEIVE'] = 'Получено каналом'
L['DTMETRICS_CHANNEL_SEND'] = 'Отправлено каналом'
L['DTMETRICS_GUILD_RECEIVE'] = 'Получено гильдией'
L['DTMETRICS_GUILD_SEND'] = 'Отправлено гильдией'
L['DTMETRICS_WARNING'] = 'Предупреждение'
L['DTMETRICS_ERROR'] = 'Ошибка'
L['DTMETRICS_CONFIG_TOTAL'] = 'Всего сообщений'
L['DTMETRICS_CONFIG_TOTAL_TOOLTIP'] = 'Отображать общее количество полученных сообщений'
L['DTMETRICS_CONFIG_AVERAGE'] = 'Среднее сообщений'
L['DTMETRICS_CONFIG_AVERAGE_TOOLTIP'] = 'Отображать среднее количество полученных сообщений'
L['DTMETRICS_CONFIG_ERROR'] = 'Всего ошибок'
L['DTMETRICS_CONFIG_ERROR_TOOLTIP'] = 'Отображать общее количество ошибок'
L['DTMETRICS_CONFIG_WARNING'] = 'Всего предупреждений'
L['DTMETRICS_CONFIG_WARNING_TOOLTIP'] = 'Отображать общее количество предупреждений'
--=========================================================================
-- Support Specific
--=========================================================================
L['SUPPORT_UAT'] = 'Тестирование пользователями'
L['DEBUG_PRINT'] = 'Нажмите любую кнопку для вывода соответствующей коллекции данных в _DebugLog'
L['DEBUG_ROSTER_TOOLTIP'] = 'Отправляют ли все члены конфедерации информацию о составе'
L['NEW_VERSION'] = '%s: Доступна новая версия, рекомендуется обновить'
L['LEAVE_GUILD'] = '%s: Игрок покинул гильдию, отключение'
L['DEBUG_LOG'] = 'Журнал отладки'
L['DEBUG_LOG_ENABLE'] = 'Включить/отключить вывод логов в аддон _DebugLog'
L['DEBUG_VERBOSITY_TOOLTIP'] = 'Уровень подробности логов аддона'
L['DEBUG_LOG_INSTANCE'] = 'Логировать в подземельях'
L['DEBUG_LOG_INSTANCE_TOOLTIP'] = 'Если выключено — логирование отключается в подземельях'
--=========================================================================
-- Setup Specific
--=========================================================================
L['SETUP_HOW_TO_INSTRUCTIONS'] = 'Для настройки XFaction для ваших гильдий вам нужны права на редактирование информации о гильдии во всех них.\n\nПереходите по вкладкам меню Настройка слева направо, заполняя все обязательные поля. Вкладка Команды — единственная необязательная.\n\nПосле заполнения всех вкладок последний шаг — добавить друг друга в друзья Battle.Net. Это создаст мост связи между фракциями. За подробностями обращайтесь к категории Поддержка.'
L['SETUP_CONFEDERATE_INSTRUCTIONS'] = 'Все поля на этой странице обязательны для правильной настройки.\n\nКоллекция гильдий называется конфедерацией. Например, конфедерация Eternal Kingdom (EK) состоит из семи гильдий. Введите желаемое название вашей конфедерации ниже.\n\nНазвание канала должно быть уникальным для ваших серверов, иначе посторонние смогут прослушивать ваш трафик.'
L['SETUP_TEAMS_INSTRUCTIONS'] = 'Настройка команд не обязательна для всех гильдий, только если у вас несколько рейдовых команд и вы хотите связывать рейдеров с их командами в чате гильдии или DataText Guild (X).\n\nПервичный ключ — инициалы команды, они должны быть уникальными в конфедерации. Можно оставлять пустые строки, если команд меньше.\n\nПри заполнении заметок игроков используйте тег [XFt:<Инициалы>] для привязки игрока к рейдовой команде.'
L['SETUP_GUILDS_INSTRUCTIONS'] = 'Введите все гильдии, которые хотите связать. Этот шаг обязателен для правильной настройки.\n\nПервичный ключ — ID гильдии, уникально идентифицирующий гильдию на всех серверах. Он должен совпадать с ID гильдии в клиенте игры, который можно получить командой:\n\n/dump C_Club.GetGuildClubId()\n\nID можно получить только будучи в соответствующей гильдии. Поэтому нужно войти в каждую гильдию и выполнить команду.'
L['SETUP_CHARACTERS'] = ' персонажей'
L['SETUP_GENERATE_INSTRUCTIONS'] = 'После ввода всей информации нажмите кнопку «Сгенерировать». В поле появится текст. Скопируйте и вставьте его в информацию о гильдии всех указанных гильдий. Не важно, куда именно (в начало, конец и т.д.).'
L['SETUP_GENERATE_TOOLTIP'] = 'Сжимать и кодировать строку конфигурации, чтобы она занимала меньше места в информации о гильдии.'
