local XFG, G = unpack(select(2, ...))
local LogCategory = 'Config'

XFG.Options.args.Debug = {
	name = XFG.Lib.Locale['DEBUG'],
	order = 1,
	type = 'group',
	args = {
		Logging = {
			order = 1,
			type = 'group',
			name = XFG.Lib.Locale['DEBUG_LOG'],
			guiInline = true,
			args = {
				Verbosity = {
					order = 1,
					type = 'range',
					name = XFG.Lib.Locale['VERBOSITY'],
					desc = XFG.Lib.Locale['DEBUG_VERBOSITY_TOOLTIP'],
					min = 0, max = 5, step = 1,
					get = function(info) return XFG.Config.Debug.Verbosity end,
					set = function(info, value) 
						XFG.Config.Debug.Verbosity = value
						XFG.Verbosity = value
					end,
				},
			},
		},
		Print = {
			order = 2,
			type = 'group',
			name = XFG.Lib.Locale['DEBUG_PRINT'],
			guiInline = true,
			args = {
				Channel = {
					order = 1,
					name = XFG.Lib.Locale['CHANNEL'],
					type = 'execute',
					disabled = function () return XFG.Config.Debug.Verbosity == 0 end,
					func = function() XFG.Channels:Print() end,
				},
				Class = {
					order = 2,
					type = 'execute',
					name = XFG.Lib.Locale['CLASS'],
					disabled = function () return XFG.Config.Debug.Verbosity == 0 end,
					func = function() XFG.Classes:Print() end,
				},
				Confederate = {
					order = 3,
					type = 'execute',
					name = XFG.Lib.Locale['CONFEDERATE'],
					disabled = function () return XFG.Config.Debug.Verbosity == 0 end,
					func = function(info) XFG.Confederate:Print() end,
				},
				Continent = {
					order = 4,
					type = 'execute',
					name = XFG.Lib.Locale['CONTINENT'],
					disabled = function () return XFG.Config.Debug.Verbosity == 0 end,
					func = function(info) XFG.Continents:Print() end,
				},
				Event = {
					order = 6,
					type = 'execute',
					name = XFG.Lib.Locale['EVENT'],
					disabled = function () return XFG.Config.Debug.Verbosity == 0 end,
					func = function(info) XFG.Events:Print() end,
				},
				Faction = {
					order = 7,
					type = 'execute',
					name = XFG.Lib.Locale['FACTION'],
					disabled = function () return XFG.Config.Debug.Verbosity == 0 end,
					func = function(info) XFG.Factions:Print() end,
				},
				Friend = {
					order = 14,
					type = 'execute',
					name = XFG.Lib.Locale['FRIEND'],
					disabled = function () return XFG.Config.Debug.Verbosity == 0 end,
					func = function(info) XFG.Friends:Print() end,
				},
				Guild = {
					order = 15,
					type = 'execute',
					name = XFG.Lib.Locale['GUILD'],
					disabled = function () return XFG.Config.Debug.Verbosity == 0 end,
					func = function(info) XFG.Guilds:Print() end,
				},
				Link = {
					order = 16,
					type = 'execute',
					name = XFG.Lib.Locale['LINK'],
					disabled = function () return XFG.Config.Debug.Verbosity == 0 end,
					func = function(info) XFG.Links:Print() end,
				},
				Node = {
					order = 17,
					type = 'execute',
					name = XFG.Lib.Locale['NODE'],
					disabled = function () return XFG.Config.Debug.Verbosity == 0 end,
					func = function(info) XFG.Nodes:Print() end,
				},
				Player = {
					order = 18,
					type = 'execute',
					name = XFG.Lib.Locale['PLAYER'],
					disabled = function () return XFG.Config.Debug.Verbosity == 0 end,
					func = function(info) XFG.Player.Unit:Print() end,
				},
				Profession = {
					order = 19,
					type = 'execute',
					name = 	XFG.Lib.Locale['PROFESSION'],
					disabled = function () return XFG.Config.Debug.Verbosity == 0 end,
					func = function(info) XFG.Professions:Print() end,
				},
				Race = {
					order = 20,
					type = 'execute',
					name = XFG.Lib.Locale['RACE'],
					disabled = function () return XFG.Config.Debug.Verbosity == 0 end,
					func = function(info) XFG.Races:Print() end,
				},
				RaiderIO = {
					order = 21,
					type = 'execute',
					name = XFG.Lib.Locale['RAIDERIO'],
					disabled = function () return XFG.Config.Debug.Verbosity == 0 end,
					func = function(info) XFG.Addons.RaiderIO:Print() end,					
				},
				Realm = {
					order = 22,
					type = 'execute',
					name = XFG.Lib.Locale['REALM'],
					disabled = function () return XFG.Config.Debug.Verbosity == 0 end,
					func = function(info) XFG.Realms:Print() end,
				},				
				Spec = {
					order = 24,
					type = 'execute',
					name = XFG.Lib.Locale['SPEC'],
					disabled = function () return XFG.Config.Debug.Verbosity == 0 end,
					func = function(info) XFG.Specs:Print() end,
				},
				Target = {
					order = 25,
					type = 'execute',
					name = XFG.Lib.Locale['TARGET'],
					disabled = function () return XFG.Config.Debug.Verbosity == 0 end,
					func = function(info) XFG.Targets:Print() end,
				},
				Team = {
					order = 26,
					type = 'execute',
					name = XFG.Lib.Locale['TEAM'],
					disabled = function () return XFG.Config.Debug.Verbosity == 0 end,
					func = function(info) XFG.Teams:Print() end,
				},
				Timer = {
					order = 27,
					type = 'execute',
					name = XFG.Lib.Locale['TIMER'],
					disabled = function () return XFG.Config.Debug.Verbosity == 0 end,
					func = function(info) XFG.Timers:Print() end,
				},
				Zone = {
					order = 28,
					type = 'execute',
					name = XFG.Lib.Locale['ZONE'],
					disabled = function () return XFG.Config.Debug.Verbosity == 0 end,
					func = function(info) XFG.Zones:Print() end,
				},
			},
		},
	},
}